apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aidacrm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aidacrm.labels" . | nindent 4 }}
automountServiceAccountToken: false
